@ECHO OFF
REM ------------------------------------------------------------
REM Example non-destructive updater for MS-DOS 6.22.
REM
REM This avoids editing AUTOEXEC.BAT or CONFIG.SYS in place.  It
REM backs them up, checks for exact marker lines with FIND, and only
REM appends the small lines this release owns.  That keeps comments,
REM spacing, local driver order, and user changes intact.
REM
REM Usage:
REM   UPDATE        Uses X: as the release source drive
REM   UPDATE D:     Uses D: as the release source drive
REM ------------------------------------------------------------

SET SRC=X:
IF %1X==X GOTO START
SET SRC=%1

:START
CLS
ECHO.
ECHO MMRCC CONFIG UPDATE
ECHO.
ECHO Source drive is %SRC%
ECHO Target drive is C:
ECHO.

IF EXIST %SRC%\CONFIG\TWEAKS.BAT GOTO SRCOK
ECHO Cannot find %SRC%\CONFIG\TWEAKS.BAT
ECHO Run UPDATE X: or UPDATE D: with the correct CD drive.
GOTO DONE

:SRCOK
IF EXIST C:\AUTOEXEC.BAT GOTO AEOK
ECHO Creating C:\AUTOEXEC.BAT
ECHO @ECHO OFF>C:\AUTOEXEC.BAT

:AEOK
IF EXIST C:\CONFIG.SYS GOTO CFGOK
ECHO Creating C:\CONFIG.SYS
ECHO DOS=HIGH,UMB>C:\CONFIG.SYS

:CFGOK
IF EXIST C:\AUTOEXEC.MMR GOTO BAEDONE
COPY C:\AUTOEXEC.BAT C:\AUTOEXEC.MMR>NUL
:BAEDONE

IF EXIST C:\CONFIG.MMR GOTO BCFDONE
COPY C:\CONFIG.SYS C:\CONFIG.MMR>NUL
:BCFDONE

IF EXIST C:\DOS\NUL GOTO DOSOK
MD C:\DOS
:DOSOK

COPY %SRC%\CONFIG\TWEAKS.BAT C:\DOS>NUL
IF EXIST %SRC%\CONFIG\VER1.1 COPY %SRC%\CONFIG\VER1.1 C:\DOS>NUL

REM Add an AUTOEXEC.BAT hook once.  FIND is native DOS 6.22.
FIND "REM MMRCC UPDATE AUTOEXEC" C:\AUTOEXEC.BAT>NUL
IF NOT ERRORLEVEL 1 GOTO AE_DONE
ECHO Updating C:\AUTOEXEC.BAT
ECHO.>>C:\AUTOEXEC.BAT
ECHO REM MMRCC UPDATE AUTOEXEC>>C:\AUTOEXEC.BAT
FIND "IF EXIST C:\DOS\TWEAKS.BAT CALL C:\DOS\TWEAKS.BAT" C:\AUTOEXEC.BAT>NUL
IF NOT ERRORLEVEL 1 GOTO AE_DONE
ECHO IF EXIST C:\DOS\TWEAKS.BAT CALL C:\DOS\TWEAKS.BAT>>C:\AUTOEXEC.BAT
:AE_DONE

REM Add CONFIG.SYS lines once. Keep this block tiny and release-owned.
FIND "REM MMRCC UPDATE CONFIG" C:\CONFIG.SYS>NUL
IF NOT ERRORLEVEL 1 GOTO CFGDONE
ECHO Updating C:\CONFIG.SYS
ECHO.>>C:\CONFIG.SYS
ECHO REM MMRCC UPDATE CONFIG>>C:\CONFIG.SYS
FIND "DEVICEHIGH=C:\DOS\SETVER.EXE" C:\CONFIG.SYS>NUL
IF NOT ERRORLEVEL 1 GOTO CFGDONE
ECHO DEVICEHIGH=C:\DOS\SETVER.EXE>>C:\CONFIG.SYS
:CFGDONE

ECHO.
ECHO Update complete.
ECHO Original files were saved as:
ECHO   C:\AUTOEXEC.MMR
ECHO   C:\CONFIG.MMR
ECHO.
ECHO Review the files, then reboot for CONFIG.SYS changes.

:DONE
SET SRC=
